resources:
- name: github-repo
  type: git
  icon: git
  source:
    uri: https://github.com/concourse/examples.git


jobs:
- name: hello-world-job
  plan:
  - get: github-repo
    trigger: true   # tell Concourse to trigger this job when new versions are emitted
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]
